In [2]:
# without coulumn tranformer - we have to concatinate all the numpy arrays, which were transformed

In [3]:
# with column tranformer we can directly make tranformation in a single line

<h1>Column Tranformer</h1>

In [10]:
import pandas as pd

In [13]:
df = pd.read_csv('covid_toy.csv')

In [37]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [38]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [14]:
df.sample(5)

    age  gender  fever   cough       city has_covid
34   74    Male  102.0    Mild     Mumbai       Yes
77    8  Female  101.0    Mild    Kolkata        No
11   65  Female   98.0    Mild     Mumbai       Yes
48   66    Male   99.0  Strong  Bangalore        No
69   73  Female  103.0    Mild      Delhi        No

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        100 non-null    int64
 1   gender     100 non-null    object
 2   fever      90 non-null     float64
 3   cough      100 non-null    object
 4   city       100 non-null    object
 5   has_covid  100 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB

In [5]:
from sklearn.compose import ColumnTransformer

In [23]:
transformer = ColumnTransformer(transformers=[
    ('t1',SimpleImputer(),['fever']),
    ('t2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('t3',OneHotEncoder(drop='first'),['gender','city'])
],remainder='passthrough')

In [8]:
# isme we are making a obejct of columntransformer 
# we have 2 attributes 
# 1 - remainder -- what to do with the columns which are not suppose to have any transformations
#                  'drop' - drop the remaining cols, 'passthrough' - dont do any chedchad to that cols
# 2 - transformers -- we pass a list containing tuples 
#                     each tuples contain object , transformer , cols on which we have to apply that

In [18]:

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [25]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [28]:
X_train_transform = transformer.fit_transform(X_train)

In [34]:
X_train_transform = pd.DataFrame(X_train_transform, columns= transformer.get_feature_names_out())

In [30]:
cols = transformer.get_feature_names_out()

In [33]:
cols

array(['t1__fever', 't2__cough', 't3__gender_Male', 't3__city_Delhi',
       't3__city_Kolkata', 't3__city_Mumbai', 'remainder__age'],
      dtype=object)

In [36]:
X_train_transform.sample(10)

,t1__fever,t2__cough,t3__gender_Male,t3__city_Delhi,t3__city_Kolkata,t3__city_Mumbai,remainder__age
47,98.000000,0.0,0.0,0.0,0.0,1.0,65.0
71,98.000000,0.0,1.0,1.0,0.0,0.0,83.0
21,104.000000,0.0,1.0,0.0,1.0,0.0,16.0
31,100.652778,1.0,0.0,0.0,0.0,0.0,42.0
35,101.000000,1.0,0.0,1.0,0.0,0.0,34.0
36,98.000000,0.0,0.0,0.0,0.0,0.0,64.0
49,99.000000,0.0,0.0,0.0,0.0,0.0,22.0
2,100.000000,0.0,1.0,0.0,1.0,0.0,27.0
79,101.000000,0.0,1.0,1.0,0.0,0.0,42.0
22,102.000000,1.0,1.0,1.0,0.0,0.0,20.0

<h1>Without Column Transformer</h1>

In [39]:
si = SimpleImputer()

In [40]:
from sklearn.model_selection import train_test_split
a_train,a_test,b_train,b_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [42]:
a_train_fever = si.fit_transform(a_train[['fever']])
a_test_fever = si.fit_transform(a_test[['fever']])
# replace by mean

In [44]:
a_train_fever.shape
#its a numpy array with 80 rows and 1 col (and the column is fever)

(80, 1)

In [45]:
oe = OrdinalEncoder(categories = [['Mild', 'Strong']])

In [55]:
a_train_cough = oe.fit_transform(a_train[['cough']])
a_test_cough = oe.fit_transform(a_test[['cough']])

In [54]:
a_train_cough.shape

(80, 1)

In [52]:
ohe = OneHotEncoder(drop = 'first')

In [56]:
a_train_gender_city = ohe.fit_transform(a_train[['gender', 'city']])

In [57]:
a_test_gender_city = ohe.fit_transform(a_test[['gender', 'city']])

In [58]:
a_train_gender_city.shape

(80, 4)

In [61]:
a_train_age = a_train.drop(columns =['gender', 'cough', 'fever', 'city']).values
a_test_age = a_test.drop(columns =['gender', 'cough', 'fever', 'city']).values

In [63]:
a_train_age.shape

(80, 1)

In [65]:
import numpy as np

In [75]:
a_train_transform = np.concatenate((a_train_age, a_train_fever, a_train_cough, a_train_gender_city), axis = 1)

In [73]:
print(a_train_age.shape)
print(a_train_fever.shape)
print(a_train_cough.shape)
print(a_train_gender_city.shape)

(80, 1)
(80, 1)
(80, 1)
(80, 4)

In [71]:
a_train_gender_city.shape

(80, 4)

In [74]:
a_train_gender_city = a_train_gender_city.toarray()

In [76]:
a_train_transform = pd.DataFrame(a_train_transform, columns= transformer.get_feature_names_out())

In [77]:
a_train_transform

,t1__fever,t2__cough,t3__gender_Male,t3__city_Delhi,t3__city_Kolkata,t3__city_Mumbai,remainder__age
0,73.0,103.000000,0.0,0.0,1.0,0.0,0.0
1,69.0,102.000000,0.0,0.0,0.0,0.0,0.0
2,65.0,99.000000,0.0,1.0,1.0,0.0,0.0
3,82.0,102.000000,1.0,0.0,0.0,0.0,0.0
4,20.0,101.000000,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...
75,55.0,100.000000,0.0,1.0,0.0,1.0,0.0
76,84.0,100.777778,0.0,0.0,0.0,0.0,0.0
77,81.0,101.000000,0.0,0.0,0.0,0.0,1.0
78,34.0,100.777778,1.0,0.0,0.0,0.0,1.0
79,82.0,100.777778,0.0,1.0,0.0,1.0,0.0