In [1]:
# 1 - impute missing values (age and embarked)

In [2]:
# 2 - one hot encoding (sex and embarked)

In [3]:
# 3 - scaling

In [4]:
# 4 - feature - selection

In [5]:
# 5 - DT

In [6]:
import pandas as pd

In [7]:
df = pd.read_csv('titanic.csv')

In [8]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [9]:
df.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)

In [12]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['Survived']),df['Survived'],test_size=0.2,random_state=42)

In [11]:
from sklearn.model_selection import train_test_split

In [13]:
X_train.head()

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
331       1    male  45.5      0      0  28.5000        S
733       2    male  23.0      0      0  13.0000        S
382       3    male  32.0      0      0   7.9250        S
704       3    male  26.0      1      0   7.8542        S
813       3  female   6.0      4      2  31.2750        S

In [14]:
y_train.sample(5)

111    0
634    0
428    0
729    0
647    1
Name: Survived, dtype: int64

In [15]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
# restarted kernal - you should always try to use the index values rather than the column name

In [16]:
# 1st step of pipeline
t1 = ColumnTransformer([('impute_age', SimpleImputer(), [2]),('impute_embarked', SimpleImputer(strategy='most_frequent'), [6])], remainder='passthrough')

In [17]:
from sklearn.preprocessing import OneHotEncoder

In [18]:
t2 = ColumnTransformer([('ohe_sex_embarked',OneHotEncoder(sparse_output=False, handle_unknown='ignore'),[1,6])], remainder='passthrough')

In [19]:
from sklearn.preprocessing import MinMaxScaler

In [20]:
# after upar vale dono transformations we will have 10 cols in total

In [21]:
t3 = ColumnTransformer([('scale', MinMaxScaler(), slice(0,10))], remainder='passthrough')

In [22]:
from sklearn.feature_selection import SelectKBest,chi2

In [23]:
t4 = SelectKBest(score_func=chi2, k=8)

In [24]:
from sklearn.tree import DecisionTreeClassifier

In [25]:
t5 = DecisionTreeClassifier()

In [26]:
from sklearn.pipeline import Pipeline,make_pipeline

In [33]:
pipe = Pipeline([('trf1',t1),('trf2',t2),('trf3',t3),('trf4',t4),('trf5',t5)])

In [34]:
# if we do only preprocessing vale steps through pipeline we we should call fit_transform

In [35]:
pipe.fit(X_train, y_train)

ValueError: could not convert string to float: 'male'